[package]
name = "sentinel2array"
version = "0.1.0"
edition = "2021"

[dependencies]
gdal = "0.17.1" 
ndarray = { version = "0.16.1", features = ["rayon"] }
proj = { version = "0.28.0", features = ["geo-types"] }
thiserror = "2.0.9"
rasters = { git="https://github.com/tsanona/rasters.rs.git", features = ["use-rayon"] }
rayon = "1.10.0"
nalgebra = "0.33.2"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async", "async_tokio"] }
ndarray-npy = "0.9.1"
rstest = "0.23.0"

[[bench]]
name = "benchmarks"
harness = false
